### ISSUE TITLE
<init-widgets immediate/> throws error "write after end"

### ISSUE THREAD

**Issue by sampology** [marko-js/marko-widgets#135]
using
```
<init-widgets immediate/>
```
without
```
<async-fragments/>
```
throws an error when using koajs
```
Listening on port 3000
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:422:15)
    at Object.BufferedWriter.flush (/home/www/markotest/node_modules/async-writer/lib/AsyncWriter.js:65:27)
    at Object.BufferedWriter.end (/home/www/markotest/node_modules/async-writer/lib/AsyncWriter.js:74:14)
    at AsyncWriter._finish (/home/www/markotest/node_modules/async-writer/lib/AsyncWriter.js:485:26)
    at AsyncWriter.handleEnd (/home/www/markotest/node_modules/async-writer/lib/AsyncWriter.js:478:22)
    at AsyncWriter.end (/home/www/markotest/node_modules/async-writer/lib/AsyncWriter.js:439:18)
    at /home/www/markotest/node_modules/marko-widgets/taglib/init-widgets-tag.js:49:18
    at next (/home/www/markotest/node_modules/async-writer/lib/AsyncWriter.js:380:17)
    at ServerResponse.<anonymous> (/home/www/markotest/node_modules/async-writer/lib/AsyncWriter.js:384:17)
    at ServerResponse.g (events.js:260:16)
```

**Comment by patrick-steele-idem** [comment]
Looks like we need update the docs for Koa need to be updated to use the Koa recommended way of supporting streaming:

```javascript
this.body = template.stream(data);
```

That solved the problem.
